
    
     const Laboratorios = [
     
     {
      facultad : 1,
      ID: 119,
      LABORATORIO: "Microscopia",
      DEPARTAMETO: "INTERFACULTAD",
      COORDINADORES: "JAVIER ANTONIO BENAVIDES MONTAÑO",
      DirElectronica: "abenavidesm@unal.edu.co",
      CEDULA: 97471873,
      LABORATORISTA: "CARLOS EDUARDO AGUDELO MORALES",
      DirElectronica: "ceagudelomo@unal.edu.co",
      CEDULA: 2474417,
      CelLaborista: 3153940372,
      ubicacion: " Edificio 30 Bloque B    Piso 1\nOficina 30-1050",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Microscopia.pdf"
     },
     
     
     
     
     {
        facultad : 1,
      ID: 646,
      LABORATORIO: "Acuacultura con enfasis en peces ornamentales",
      DEPARTAMETO: "CIENCIA ANIMAL",
      COORDINADORES: "CARLOS ALBERTO JARAMILLO CRUZ",
      DirElectronica: "cajaramillocr@unal.edu.co",
      CEDULA: 16776208,
      ubicacion: "Bloque 70 - Zootecnia 1, 1 Piso Oficina 70-1020",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Acuicultura_peces.pdf"
     },
     {
        facultad : 1,
      ID: 160,
      LABORATORIO: "Anatomia y fisiologia animal",
      DEPARTAMETO: "CIENCIA ANIMAL",
      COORDINADORES: "JAVIER ANTONIO BENAVIDES MONTAÑO",
      DirElectronica: "abenavidesm@unal.edu.co",
      CEDULA: 97471873,
      LABORATORISTA: "IBETH YAJAIRA CORONEL ORTIZ",
      DirElectronica: "iycoronelo@unal.edu.co",
      CEDULA: 37332628,
      CelLaborista: 3113222990,
      ubicacion: "Edificio 90 Zootecnia 1, 1 piso Oficina 90-1010\/30",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Anatomia_fisiologia_animal.pdf"
     },
     {
        facultad : 1,
      ID: 231,
      LABORATORIO: "Biología",
      DEPARTAMETO: "CIENCIAS BIOLOGICAS",
    COORDINADORES: "AMANDA ORTIZ ESCOBAR",
      DirElectronica: "aortizes@unal.edu.co",
      CEDULA: 31269961,
      LABORATORISTA: "JUAN GABRIEL OSORIO RUEDA",
      DirElectronica: "jgosorior@unal.edu.co",
      CEDULA: 1093738930,
      CelLaborista: 3103629413,
      ubicacion: "Edificio 30 Bloque B, Piso 1 Ofcina 30-1120",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Biologia.pdf"

     },
     {
        facultad : 1,
      ID: 159,
      LABORATORIO: "Biología molecular",
      DEPARTAMETO: "CIENCIAS BIOLOGICAS",
    COORDINADORES: "JUAN CARLOS RINCÓN FLOREZ",
      DirElectronica: "jcrincon@unal.edu.co",
      CEDULA: 1036602447,
      LABORATORISTA: "ALEJANDRO MORALES GRAJALES",
      DirElectronica: "almoralesgr@unal.edu.co",
      CEDULA: 1113657834,
      CelLaborista: 3183789400,
      ubicacion: "Edificio 30 Bloque  B, Piso 3 Oficina 30-3070\/3080",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Biologia_molecular.pdf"
     },
     {
        facultad : 1,
      ID: 302,
      LABORATORIO: "Botanica",
      DEPARTAMETO: "CIENCIAS BIOLOGICAS",
    COORDINADORES: "JHON ALBEIRO OCAMPO PEREZ",
      DirElectronica: "jaocampop@unal.edu.co",
      CEDULA: 75063076,
      LABORATORISTA: "MARIA CLAUDIA CORTES VALDERRAMA",
      DirElectronica: "mccortesv@unal.edu.co",
      CEDULA: 66763974,
      CelLaborista: 3174407629,
      ubicacion: "Edificio 30 Bloque  B, Piso 1 Oficina 30-1030\/40",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Botanica.pdf"
     },
     {
        facultad : 1,
      ID: 291,
      LABORATORIO: "CEUNP",
      DEPARTAMETO: "CIENCIAS AGRICOLAS",
    COORDINADORES: "CARLOS GERMAN MUÑOZ PEREA",
      DirElectronica: "cgmunozp@unal.edu.co",
      CEDULA: 16752279,
      LABORATORISTA: "ARMANDO ZAPATA VALENCIA ",
      DirElectronica: "azapatav@unal.edu.co",
      CelLaborista: 3137337602,
      ubicacion: "Via Candelaria",
      link: "#"
     },
     {
        facultad : 1,
      ID: 391,
      LABORATORIO: "citogenetica",
      DEPARTAMETO: "CIENCIAS BIOLOGICAS",
      COORDINADORES: "AMANDA ORTIZ ESCOBAR",
      DirElectronica: "aortizes@unal.edu.co",
      CEDULA: 31269961,
      ubicacion: "Edificio 30 Bloque B, Piso 1 Oficina 30-1060",
      link: "#"
     },
     {
        facultad : 1,
      ID: 168,
      LABORATORIO: "Diagnostico vegetal",
      DEPARTAMETO: "CIENCIAS AGRICOLAS",
      COORDINADORES: "CARLOS IVAN CARDOZO CONDE",
      DirElectronica: "cicardozoc@unal.edu.co",
      CEDULA: 16606902,
      LABORATORISTA: "DORA LILIA JARAMILLO COBO",
      DirElectronica: "dljaramilloc@unal.edu.co",
      CEDULA: 66764716,
      CelLaborista: 3016773678,
      ubicacion: "Edificio 30 Bloque  B, Piso 3 Oficina 30-3090",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Diagnostico_vegetal.pdf"
     },
     {
        facultad : 1,
      ID: 188,
      LABORATORIO: "Entomologia, acarologia ",
      DEPARTAMETO: "CIENCIAS AGRICOLAS",
      LABORATORISTA: "ALFREDO RIVERA PERALTA",
      DirElectronica: "ariverap@unal.edu.co",
      CEDULA: 16276340,
      CelLaborista: 3155692090,
      ubicacion: "Edificio 30 Bloque B , Piso  3 Oficina 30-3050",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Entomologia_acarologia_museo.pdf"
     },
     {
        facultad : 1,
      ID: 301,
      LABORATORIO: "Fisiologia vegetal, semillas y casas de mallas",
      DEPARTAMETO: "CIENCIAS AGRICOLAS",
    COORDINADORES: "MARÍA SARA MEJÍA DE TAFUR",
      DirElectronica: "msmejiat@unal.edu.co ",
      CEDULA: 24308826,
      LABORATORISTA: "ALEXANDER RAMIREZ RAMIREZ",
      DirElectronica: "aleramirezra@unal.edu.co",
      CEDULA: 94520333,
      CelLaborista: 3015040894,
      ubicacion: "Edificio Casa de Mallas 120 A Oficina 120A-1040",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Entomologia_acarologia_museo.pdf"
     },
     {
        facultad : 1,
      ID: 162,
      LABORATORIO: "Genética",
      DEPARTAMETO: "CIENCIA ANIMAL",
    COORDINADORES: "JUAN CARLOS RINCÓN FLOREZ ",
      DirElectronica: "jcrincon@unal.edu.co",
      CEDULA: 1036602447,
      LABORATORISTA: "DORA MONICA IBARRA ESPINOSA",
      DirElectronica: "dmibarrae@unal.edu.co",
      CEDULA: 59794382,
      CelLaborista: 3165722329,
      ubicacion: "Edificio 30 Bloque  B,  Piso 3 Oficina 30-3040",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Genetica.pdf"
     },
     {
        facultad : 1,
      ID: 358,
      LABORATORIO: "Granja mario gonzalez aranda",
      DEPARTAMETO: "CIENCIA ANIMAL",
    COORDINADORES: "SANÍN ORTIZ GRISALES",
      DirElectronica: "sortizg@unal.edu.co",
      CEDULA: 16265144,
      LABORATORISTA: "CRISTIAN CAMILO SOLARTE BACCA",
      DirElectronica: "ccsolarteb@unal.edu.co",
      CEDULA: 1087026535,
      CelLaborista: 3176261975,
      ubicacion: "Via Candelaria",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Granja_MGA.pdf"
     },
     {
        facultad : 1,
      ID: 342,
      LABORATORIO: "Herbario jose cuatrecasas arumi",
      DEPARTAMETO: "CIENCIAS BIOLOGICAS",
    COORDINADORES: "LUIS EDUARDO FORERO PINTO",
      DirElectronica: "leforerop@unal.edu.co",
      CEDULA: 19103398,
      LABORATORISTA: "FREDY ARIOSTO CORREDOR CRISTANCHO",
      DirElectronica: "facorredorc@unal.edu.co",
      CEDULA: 79828408,
      CelLaborista: 3132264691,
      ubicacion: "Edificio 30 Bloque B,  Piso 2 Oficina 30-2030\/40",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Herbario_jose_cuatrecasas.pdf"

     },
     {
        facultad : 1,
      ID: 234,
      LABORATORIO: "Nutricion animal",
      DEPARTAMETO: "CIENCIA ANIMAL",
      COORDINADORES: "LUZ STELLA MUÑOZ ARBOLEDA",
      DirElectronica: "lsmunoza@unal.edu.co",
      CEDULA: 31171076,
      LABORATORISTA: "ARLERT JHOJANNA GIRALDO GIL",
      DirElectronica: "arjgiraldogi@unal.edu.co",
      CEDULA: 43206542,
      CelLaborista: 3104328622,
      ubicacion: "Edificio 60 Piso 2 Oficina160-2010\/30",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Herbario_jose_cuatrecasas.pdf"
     },
     {
        facultad : 1,
      ID: 831,
      LABORATORIO: "Parasitologia, inmunologia, y enfermedades infecciosas (parenei)",
      DEPARTAMETO: "CIENCIA ANIMAL",
    COORDINADORES: "JAVIER ANTONIO BENAVIDES MONTAÑO",
      DirElectronica: "abenavidesm@unal.edu.co",
      CEDULA: 97471873,
      CelLaborista: 3185003539,
      ubicacion: "Edificio 160 Piso 1 Oficina 160-2040",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Parasitologia_Inmunologia_PARINEI.pdf"
     },
     {
        facultad : 1,
      ID: 331,
      LABORATORIO: "Reproduccion animal",
      DEPARTAMETO: "CIENCIA ANIMAL",
    COORDINADORES: "RÓMULO CAMPOS GAONA",
      DirElectronica: "rcamposg@unal.edu.co",
      CEDULA: 6578332,
      LABORATORISTA: "LUIS CARLOS CALLE ESPINOSA",
      DirElectronica: "lccallee@unal.edu.co",
      CEDULA: 16268119,
      CelLaborista: 3105438128,
      ubicacion: "Edificio 60 Piso 1 Oficina 1011-1010",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Reproduccion_animal.pdf"
     },
     {
        facultad : 1,
      ID: 326,
      LABORATORIO: "Reserva nacional forestal bosque de yotoco",
      DEPARTAMETO: "CIENCIA ANIMAL",
    COORDINADORES: "CARLOS ALBERTO JARAMILLO CRUZ",
      DirElectronica: "cajaramillocr@unal.edu.co",
      CEDULA: 16776208,
      LABORATORISTA: "VALENTIN HIDALGO LLANTEN ",
      DirElectronica: "vhidalgol@unal.edu.co",
      CelLaborista: 3154714758,
      ubicacion: "Yotoco",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Reserva_nacional_forestal_yotoco.pdf"
     },
     {
        facultad : 1,
      ID: 298,
      LABORATORIO: "Sanidad y microbiologia agricola",
      DEPARTAMETO: "CIENCIAS AGRICOLAS",
    COORDINADORES: "CARLOS GERMAN MUÑOZ PEREA",
      DirElectronica: "cgmunozp@unal.edu.co",
      CEDULA: 16752279,
      LABORATORISTA: "CAMILO ERNESTO PERDOMO AVILA",
      DirElectronica: "ceperdomoa@unal.edu.co",
      CEDULA: 1113657402,
      CelLaborista: 3158983392,
      ubicacion: "Edificio 30 Bloque B,  Piso 2 Oficina 30-2070\/110",
      link: "#"
     },
     
     {
      facultad : 1,
      ID: 73,
      LABORATORIO: "Semillas",
      DEPARTAMETO: "CIENCIA ANIMAL",
    COORDINADORES: "SANIN ORTIZ GRISALES",
      DirElectronica: "sortizg@unal.edu.co",
      CEDULA: 16265144,
      ubicacion: "Edificio 90 Piso 1 Oficina 90-1040",
      link: "#"
     },
     
     
    
     
     {
      facultad : 2,
      ID: 169,
      LABORATORIO: "ANALISIS AMBIENTAL",
      DEPARTAMETO: "INGENIERIA ",
    COORDINADORES: "DOIAN PRATO GARCIA",
      DirElectronica: "dpratog@unal.edu.co",
      CEDULA: 88216780,
      LABORATORISTA: "CARLOS EDUARDO MADRIÑAN PALOMINO",
      DirElectronica: "cemadrinanp@unal.edu.co",
      CEDULA: 16268829,
      CelLaborista: 3108952615,
      ubicacion: "Bloque 40,  2 Piso Oficina 40-2100",
      link: "www.palmira.unal.edu.co/images/descargas/Laboratorios/Analisis_ambiental.pdf"
     },
     {
        facultad : 2,
      ID: 161,
      LABORATORIO: "VOY AQUI BIOCONVERSION",
      DEPARTAMETO: "INGENIERIA ",
    COORDINADORES: "LILIANA SRENA COOK",
      DirElectronica: "lserna@unal.edu.co",
      CEDULA: 24624547,
      LABORATORISTA: "OMAR VLADIMIR PABON RODRIGUEZ",
      DirElectronica: "ovpabonro@unal.edu.co",
      CEDULA: 11259249,
      CelLaborista: 3203355049,
      ubicacion: "Edificio 80,  Piso 1 Oficina 80-1040"
     },
     {
        facultad : 2,
      ID: 842,
      LABORATORIO: "CO-CREACION E INNOVACION SOCIAL",
      DEPARTAMETO: "DISEÑO",
    COORDINADORES: "JOHN JAIRO CARDOZO VÁSQUEZ",
      DirElectronica: "jjcardozov@unal.edu.co ",
      CEDULA: 80443016,
      LABORATORISTA: "LINA PAOLA SOTO BENJUMEA",
      DirElectronica: "lpsotob@unal.edu.co",
      CEDULA: 1113682338,
      CelLaborista: 3154053651,
      ubicacion: "Edificio 20 - Biblioteca y Post-Grado"
     },
     {
        facultad : 2,
      ID: 844,
      LABORATORIO: "CIENCIAS DE LA TIERRA Y DEL AMBIENTE",
      DEPARTAMETO: "INGENIERIA ",
    COORDINADORES: "ENRIQUE ALEJANDRO TORRES PRIETO",
      DirElectronica: "eatorresp@unal.edu.co",
      CEDULA: 16832745,
      LABORATORISTA: "Sin Espacio"
     },
     {
        facultad : 2,
      ID: 392,
      LABORATORIO: "DISEÑO Y MECANIZADO ASISTIDO POR COMPUTADOR (DYMAC)",
      DEPARTAMETO: "DISEÑO",
    COORDINADORES: "JOHN JAIRO CARDOZO VÁSQUEZ",
      DirElectronica: "jjcardozov@unal.edu.co ",
      CEDULA: 80443016,
      LABORATORISTA: "OMAR ANDRES OCAMPO GUERRERO",
      DirElectronica: "oaocampog@unal.edu.co",
      CEDULA: 1113649287,
      CelLaborista: 3182395980,
      ubicacion: "Edificio Operaciones Unitarias 150 Bloque central  Piso 1 Oficina 150-2120 "
     },
     {
        facultad : 2,
      ID: 207,
      LABORATORIO: "FABRICACION Y SIMULACION DE MODELOS FISICOS",
      DEPARTAMETO: "DISEÑO",
    COORDINADORES: "JOHN JAIRO CARDOZO VÁSQUEZ",
      DirElectronica: "jjcardozov@unal.edu.co ",
      CEDULA: 80443016,
      LABORATORISTA: "VICTOR FABIO CAMACHO",
      DirElectronica: "vfcamacho@unal.edu.co",
      CEDULA: 16266642,
      CelLaborista: 3177292062,
      ubicacion: "Taller  Maquinaria 120 Oficina 120-1050"
     },
     {
        facultad : 2,
      ID: 232,
      LABORATORIO: "FACTORES HUMANOS Y ERGONOMÍA",
      DEPARTAMETO: "DISEÑO",
    COORDINADORES: "JOHN JAIRO CARDOZO VÁSQUEZ",
      DirElectronica: "jjcardozov@unal.edu.co ",
      CEDULA: 80443016,
      ubicacion: "Edificio 10 Torre Administrativa, piso 2 Oficina 10-2110"
     },
     {
        facultad : 2,
      ID: 196,
      LABORATORIO: "FISICA",
      DEPARTAMETO: "CIENCIAS BASICAS",
    COORDINADORES: "GIRALDO JIMENEZ CHAPPOTIN",
      DirElectronica: "cgiraldoj@unal.edu.co",
      CEDULA: 1113535182,
      LABORATORISTA: "ANDRÉS FELIPE ZUÑIGA HOLGUIN",
      DirElectronica: "anzunigah@unal.edu.co",
      CEDULA: 1116269648,
      CelLaborista: 3175908977,
      ubicacion: "Edificio Operaciones Unitarias 150 Bloque 2 Piso 1 Oficina150-1060"
     },
     {
        facultad : 2,
      ID: 212,
      LABORATORIO: "INVESTIGACIONES AMBIENTALES",
      DEPARTAMETO: "FIA",
    COORDINADORES: "LUZ STELLA CADAVID RODRÍGUEZ",
      DirElectronica: "lscadavidr@unal.edu.co ",
      CEDULA: 52039989,
      LABORATORISTA: "MARIA ENITH ARIAS JARAMILLO",
      DirElectronica: "meariasj@unal.edu.co",
      CEDULA: 31626256,
      CelLaborista: 3057366862,
      ubicacion: "Bloque 40 Piso 1 Oficina 40-1120"
     },
     {
        facultad : 2,
      ID: 204,
      LABORATORIO: "MATERIALES",
      DEPARTAMETO: "DISEÑO",
    COORDINADORES: "JOHN JAIRO CARDOZO VÁSQUEZ",
      DirElectronica: "jjcardozov@unal.edu.co ",
      CEDULA: 80443016,
      LABORATORISTA: "ORLANDO DARIO MORALES TAMAYO",
      DirElectronica: "odmoralest@unal.edu.co",
      CEDULA: 94375647,
      CelLaborista: 3174316146,
      ubicacion: "Edificio 120 Taller Maquinaria Piso 1 Oficina 120-1070"
     },
     {
        facultad : 2,
      ID: 233,
      LABORATORIO: "MECANICA DE FLUIDOS, HIDRAULICA Y RIEGOS",
      DEPARTAMETO: "INGENIERIA ",
    COORDINADORES: "ENRIQUE ALEJANDRO TORRES PRIETO",
      DirElectronica: "eatorresp@unal.edu.co",
      CEDULA: 16832745,
      LABORATORISTA: "LUIS ANGEL MURILLO LOZANO",
      DirElectronica: "lamurillolo@unal.edu.co",
      CEDULA: 16988416,
      CelLaborista: 3146099076,
      ubicacion: "Edificio Operaciones Unitarias 150  1 Piso Oficina 150-1100\/1110"
     },
     {
        facultad : 2,
      ID: 340,
      LABORATORIO: "MECANIZACION AGRICOLA Y MECANISMOS",
      DEPARTAMETO: "INGENIERIA ",
    COORDINADORES: "OSCAR CHAPARRO ANAYA ",
      DirElectronica: "ochaparroa@unal.edu.co",
      CEDULA: 91245878,
      LABORATORISTA: "CESAR AUGUSTO MEDINA MOSQUERA",
      DirElectronica: "camedinamo@unal.edu.co",
      CEDULA: 10481794,
      CelLaborista: 3006234986,
      ubicacion: "Edificio 120 Taller Maquinaria Oficina 120-1120"
     },
    
     {
        facultad : 2,
      ID: 170,
      LABORATORIO: "OPERACIONES UNITARIAS Y DE PROCESOS AGROINDUSTRIALES",
      DEPARTAMETO: "INGENIERIA ",
    COORDINADORES: "PEDRO VANEGAS MAHECHA",
      DirElectronica: "pvanegasmah@unal.edu.co",
      CEDULA: 19341089,
      LABORATORISTA: "CARLOS ANDRES RENGIFO GUERRERO",
      DirElectronica: "carengifog@unal.edu.co",
      CEDULA: 1113632653,
      CelLaborista: 3186020308,
      ubicacion: "Edificio 150  1 Piso"
     },
     {
        facultad : 2,
      ID: 227,
      LABORATORIO: "QUIMICA, BIOQUIMICA Y FITOQUIMICA",
      DEPARTAMETO: "CIENCIAS BASICAS",
    COORDINADORES: "HARLEN GERARDO TORRES CASTAÑEDA",
      DirElectronica: "hgtorresc@unal.edu.co",
      CEDULA: 16495943,
      LABORATORISTA: "ADRIANA VALENCIA CORREA\n",
      DirElectronica: "avalenciac@unal.edu.co",
      CEDULA: 31980185,
      CelLaborista: 3103937474,
      ubicacion: "Edificio 40 Bloque C ,  1 Piso"
     },
    
     {
        facultad : 2,
      ID: 176,
      LABORATORIO: "SISTEMAS DE INFORMACIÓN GEOGRÁFICA, TOPOGRAFÍA Y FOTOINTERPRETACIÓN",
      DEPARTAMETO: "INGENIERIA ",
    COORDINADORES: "JOHN JOSEPHRAJ SELVARAJ ",
      DirElectronica: "jojselvaraj@unal.edu.co",
      CEDULA: 339884,
      LABORATORISTA: "JOSE WILSON MURILLO LOZANO",
      DirElectronica: "jwmurillol@unal.edu.co",
      CEDULA: 16989019,
      CelLaborista: 3183417733,
      ubicacion: "Bloque 40 , Piso 2Oficina 40-2040 "
     },
     {
        facultad : 2,
      ID: 367,
      LABORATORIO: "SUELOS: AREA FISICA",
      DEPARTAMETO: "INGENIERIA ",
    COORDINADORES: "SANDRO NOLAN IPAZ CUASTUMAL",
      DirElectronica: "snipazc@unal.edu.co",
      CEDULA: 94425211,
      LABORATORISTA: "MARIA ANDREA VILLEGAS TORRES",
      DirElectronica: "mavillegast@unal.edu.co",
      CEDULA: 66785350,
      CelLaborista: 3153827244,
      ubicacion: "Bloque 40 Piso 3 Oficina 40-3080\/3090"
     },
     
     {
        facultad : 2,
      ID: 230,
      LABORATORIO: "SUELOS: AREA QUIMICA ",
      DEPARTAMETO: "INGENIERIA ",
    COORDINADORES: "SANDRO NOLAN IPAZ CUASTUMAL",
      DirElectronica: "snipazc@unal.edu.co",
      CEDULA: 94425212,
      LABORATORISTA: "JUAN PABLO SANCHEZ ECHEVERRI",
      DirElectronica: "jpsancheze@unal.edu.co",
      CEDULA: 1017174228,
      ubicacion: "Bloque 40 Piso 2 Oficina 40-2090"
     },
     
     {
        facultad : 2,
      ID: 229,
      LABORATORIO: "TECNOLOGIA DE CARNES ",
      DEPARTAMETO: "INGENIERIA ",
    COORDINADORES: "JOSE IGOR HLEAP ZAPATA",
      DirElectronica: "jihleapz@unal.edu.co",
      CEDULA: 19458956,
      LABORATORISTA: "JAIRO MOSQUERA ESCOBAR",
      DirElectronica: "jmosquerae@unal.edu.co",
      CEDULA: 19325575,
      CelLaborista: 3204121496,
      ubicacion: "Bloque 80,  Piso 1 Oficina 80-1010"
     },
     {
        facultad : 2,
      ID: 385,
      LABORATORIO: "TECNOLOGIA DE FRUTAS Y HORTALIZAS",
      DEPARTAMETO: "INGENIERIA ",
      COORDINADORES: "LUIS EDUARDO ORDOÑEZ SANTOS",
      DirElectronica: "leordonezs@unal.edu.co",
      CEDULA: 88175048,
      LABORATORISTA: "MARCO TULIO ALVAREZ GARCIA",
      DirElectronica: "mtalvarezg@unal.edu.co",
      CEDULA: 94317691,
      CelLaborista: 3136508717,
      ubicacion: "Edificio Operaciones Unitarias 150 Piso 1 Oficina 150-1250"
     },
     {
        facultad : 2,
      ID: 173,
      LABORATORIO: "TECNOLOGIA DE LECHES ",
      DEPARTAMETO: "INGENIERIA ",
      COORDINADORES: "MARGARITA MARIA ANDRADE MAHECHA",
      DirElectronica: "mmandradem@unal.edu.co",
      CEDULA: 65785981,
      LABORATORISTA: "LILIANA PATRICIA ESCARRIA PARRA",
      DirElectronica: "lpescarriap@unal.edu.co",
      CEDULA: 31159731,
      CelLaborista: 3184570465,
      ubicacion: "Edificio 70 Piso 1 Oficina 70-1030-1040"
     }
    ]
    